### ISSUE TITLE
Error whem starting the example app

### ISSUE THREAD

**Issue by klhmeyer** [ScalaConsultants/mesmer-akka-agent#227]
When I start the example according to the documentation on Windows 10 (sbt "project example" runWithAgent), I get an error:
running (fork) example.Boot
[error] Exception in thread "main" java.lang.reflect.InvocationTargetException
[info] FATAL ERROR in native method: processing of -javaagent failed
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
[error]         at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
[error] Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigFactory
[error]         at io.scalac.mesmer.agent.Boot$.premain(Boot.scala:23)
[error]         at io.scalac.mesmer.agent.Boot.premain(Boot.scala)
[error]         ... 6 more
[error] Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory
[error]         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
[error]         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]         ... 8 more
[error] Nonzero exit code returned from runner: 1
[error] (Compile / run) Nonzero exit code returned from runner: 1

**Comment by lgajowy** [comment]
Closing due to lack of activity but feel free to reopen in case it's still an issue.
