### ISSUE TITLE
Error on example project startup

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer-akka-agent#241]
Steps to reproduce: 

```
cd example/docker; docker-compose up
```

Then,  in the project root:

```
sbt "project example" runWithAgent
```

This at some point yields the following console log: 

```
[error] Could not load Logmanager "wvlet.log.AirframeLogManager"
[error] java.lang.ClassNotFoundException: wvlet.log.AirframeLogManager
[error]         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[error]         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[error]         at java.logging/java.util.logging.LogManager$1.run(LogManager.java:239)
[error]         at java.logging/java.util.logging.LogManager$1.run(LogManager.java:223)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[error]         at java.logging/java.util.logging.LogManager.<clinit>(LogManager.java:222)
[error]         at java.logging/java.util.logging.Logger.demandLogger(Logger.java:649)
[error]         at java.logging/java.util.logging.Logger.getLogger(Logger.java:718)
[error]         at java.logging/java.util.logging.Logger.getLogger(Logger.java:702)
[error]         at io.grpc.ManagedChannelRegistry.<clinit>(ManagedChannelRegistry.java:40)
[error]         at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
[error]         at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
[error]         at io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:117)
[error]         at io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporterBuilder.build(OtlpGrpcMetricExporterBuilder.java:128)
[error]         at io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter.getDefault(OtlpGrpcMetricExporter.java:30)
[error]         at example.Boot$.initOpenTelemetryMetrics(Boot.scala:47)
[error]         at example.Boot$.startUp(Boot.scala:77)
[error]         at example.Boot$.delayedEndpoint$example$Boot$1(Boot.scala:126)
[error]         at example.Boot$delayedInit$body.apply(Boot.scala:33)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:76)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at example.Boot$.main(Boot.scala:33)
[error]         at example.Boot.main(Boot.scala)
```

Probably a missing dependency that needs to be added to example deps.

**Comment by lgajowy** [comment]
https://github.com/ScalaConsultants/mesmer-akka-agent/pull/233#issuecomment-992439070 will be solved separately as is a non blocking issue.
