### ISSUE TITLE
Test opentelemetry extension jar with otel agent and an external akka aplication (not "example" project) 

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer-akka-agent#334]
That has to be done before releasing the open telemetry extension to be sure users can work with it. 

Work Items: 
 - identify problems with the published jar (if any)
 - fix them

[Snapshot jars](https://oss.sonatype.org/content/repositories/snapshots/io/scalac/) can be used for the job.

**Comment by lgajowy** [comment]
Getting: 

```
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.NoClassDefFoundError: scala/$less$colon$less
	at io.scalac.mesmer.agent.config.MesmerConfigPropertySourceProvider.getProperties(MesmerConfigPropertySource.scala)
	at io.scalac.mesmer.agent.config.MesmerConfigPropertySource.getProperties(MesmerConfigPropertySource.java:13)
	at io.opentelemetry.javaagent.tooling.config.ConfigInitializer.loadSpiConfiguration(ConfigInitializer.java:47)
	at io.opentelemetry.javaagent.tooling.config.ConfigInitializer.initialize(ConfigInitializer.java:30)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.<clinit>(AgentInstaller.java:81)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:65)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:37)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:55)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.ClassNotFoundException: scala.$less$colon$less
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 15 more
```

When running with latest snapshot: https://oss.sonatype.org/content/repositories/snapshots/io/scalac/mesmer-otel-extension_2.13/0.5.1+88-52f407af-SNAPSHOT/mesmer-otel-extension_2.13-0.5.1+88-52f407af-SNAPSHOT.jar

**Comment by lgajowy** [comment]
Could that be due to the fact that we bumped the Scala version to 2.13 but not on the CI?

**Comment by lgajowy** [comment]
That line from GH Actions would suggest that: 

> [info] [launcher] getting Scala 2.12.15 (for sbt)...

**Comment by lgajowy** [comment]
The ci is not the problem. When i use jars published using `publishLocal` jar i get the same error. Looking further

**Comment by lgajowy** [comment]
Yeah - we need to publish a fat jar for the extension - this is explained in the extension example's build.gradle: 
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/build.gradle#L4

**Comment by lgajowy** [comment]
Tested with example application from Akka site (HTTP quickstart scala). Fixed the detected problem with publish here: https://github.com/ScalaConsultants/mesmer/issues/373 

Other than that I was able to successfully mesmer with the app. Closing
