### ISSUE TITLE
Runtime exception on jdk11

### ISSUE THREAD

**Issue by ornel-lloyd-edano** [ScalaConsultants/mesmer-akka-agent#343]
1. checkout main branch and pull latest

2. set environment to Java 11

> `ornellloydedano@Ornels-MBP mesmer-akka-agent % sdk current java
> 
> Using java version 11.0.11.j9-adpt
> 
> ornellloydedano@Ornels-MBP mesmer-akka-agent % `

3. sbt clean assembly

4. sbt "project example" runWithMesmerAgent

> `[info] [Byte Buddy] ERROR akka.remote.artery.jfr.TransportStarted [jdk.internal.loader.ClassLoaders$AppClassLoader@6061772, unnamed module @ea4e733e, Thread[main,5,main], loaded=false]
> [info] net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for jdk.jfr.Event
> [info] 	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:167)
> [info] 	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1088)
> [info] 	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:8349)
> [info] 	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getSuperClass(TypeDescription.java:3600)
> [info] 	at net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:391)
> [info] 	at net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:357)
> [info] 	at net.bytebuddy.matcher.HasSuperTypeMatcher.doMatch(HasSuperTypeMatcher.java:53)
> [info] 	at net.bytebuddy.matcher.HasSuperTypeMatcher.doMatch(HasSuperTypeMatcher.java:31)
> [info] 	at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
> [info] 	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:146)
> [error] Exception in thread "main" java.lang.NoClassDefFoundError: jdk.jfr.Event
> [info] 	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.`

**Comment by lgajowy** [comment]
This was happening for mesmer agent but we should check if the otel extension works as well
